# Vitenskapsfilosofi

Vitskapeleg filosofi og metode har over lang tid blitt sett på frå ulike synsvinklar der ulike meningar har kome fram for å prøve å beskrive kva som er vitskap og ikkje. Nokon av dei som har prøvd å svare på spørsmålet om kva som er vitskap og ikkje meiner at vitskapen er induktiv. Den induktive vitskapen basera seg på observasjonar og empirisk data der ein skal komme fram til argumenter basert på premisser. Det blir kalla for eit induktivt gyldig argument når premisser gir god støtte og fører til ein konklusjon som er sannsynleg. Ein konkluderer aldri med at konklusjonen ikkje kan vere falsk, men at den eventuelt er sannsynleg. Ved denne metoden for vitskap ønsker man å bekrefte ulike ting i verdsbiletet i motsetning til deduktiv vitskap der ein ønske å falsifisere påstandar som ikkje stemmer. Ein tilhengar av den deduktive vitskapen ved namn Karl Popper meinte at den induktive metoden ikkje kunne kallast vitskap på grunn av induksjonsproblemet David Hume hadde forklart. 

Hume forklarte at induktiv vitskap ikkje kunne rettferdiggjerast på grunn av at induksjon ikkje kunne gjerast utan antyding om at fortid og framtid vil likne på kvarandre. Forventningane om kva som skal skje i framtida vil vere basert på erfaringar frå noko som har skjedd frå før, men det som er med erfaringar er at det fortel oss om kva som har skjedd og ikkje kva som skal skje. Han brukte eit eksempel om at sola vil stå opp i morgon basert på at sola har stått opp alle dagar fram til no, men det kan ein ikkje gyldig argumentere for utan å anta at naturens lover er stabile og framtida vil likne på fortida. Fornuften kan heller ikkje rettferdiggjere det fordi vi ikkje kan sei at dei naturlege lovene vil vere konstante i all fortid ifølge Humes.

Fornuften har over mange tilfelle fungert slik at ein finner ut av ting og kan komme fram til nye ting. Eg meiner fornufta har over lang tid vert med på å utvikle menneskeheita til det den er i dag og den fungerer ofte mot kva som kan vere sannsynleg. Grunnlaget for å kalle noko sannsynleg basert på fornuft vil vere kunnskap ein har lært seg, og den kunnskapen kjem frå erfaringar gjennom menneskets historie. Erfaringsgrunnlaget til menneskeheita kan ein sjå på som så stort at ein kan argumentere for at fornufta kan komme fram til ein sannsynleg vurdering for at noko skal skje. Ved å godta at ein ved fornuft kan vurdere sannsynet godt nok til å rettferdiggjere induktive konklusjonar så vil ein påstå at det er vitskap. Sjølv om det funkar i dagleg tankegang og det kan virke sannsynleg meiner Hume at det ikkje vil vere løysing på problemet fordi svaret hans på eit slikt argument kjem til å bli at det likevel er ein antyding om framtida og då kan vi ikkje rasjonelt argumentere for at framtida vil likne på fortida.   




Bayesianismen er ein retning innanfor vitskapsteorien som meiner at ein ved hjelp av sannsynsrekningar frå Thomas Bayes matematiske modell skal beskrive kva som er vitskap. Bayes er kjent for likninga bayenismen brukar for å berekne sannsynet til ein hypotese. Likninga P(H|E) = P(H)P(E|H)/P(E) beskriver sannsynet for at H er sann gitt at E stemmer. For eksempel kan ein tenke seg ein kan rekne ut ein sannsynet for at det regnar i morgon gitt at det er overskya. For å komme fram til det må ein gonge sannsynet for at det regnar er sann utan at vi har vurdert sannsynet for at det er overskya P(H) (også kalla priori-sannsyn), med sannsynet for at det er overskya gitt at det regner P(E|H), og så skal det delast på sannsynet for at det er overskya er sann P(E). Basert på likninga meiner Bayenistiske teoretikarar at dei tildel eit nummer mellom null og ein som skal representere kor sannsynleg ein hypotese kan vere. Om verdien på reknestykket er nærare ein indikerer det høgare sannsynet, og med ein verdi nærare null indikere det lågare sannsyn. Ideen om å berekne seg fram til ein verdi som kan beskrive sannsynet for at noko stemmer skal redusere usikkerheit ved å få eit tall til å vurdere og samanlikne ulike hypotesar, og i tillegg til at ny informasjon som kjem fram kontinuerleg vil oppdatere berekningane. 

Sannsyna i Bayesianismen kan sjåast på som subjektive vurderingar av trua ein har på at ein hypotese stemmer. I motsetning til ein frekvensorientert tolking av sannsynet som fortel at ein hending som skjer med ein hyppig frekvens vil vere meir sannsynleg så meiner bayesianismen at sannsynet er ei gradert tru på at ein hypotese stemmer basert på tilgjengeleg informasjon ein har. Det kan tolkast som individuelle vurderingar av sannsynet, gitt tilgjengeleg informasjon vi har. Sannsynet vil kontinuerleg bli oppdatert av informasjonen som blir tilgjengeleg som fungerer bra, men vurderingar kan bli ulike basert på ulik subjektiv vurdering av kor sannsynleg priori sannsynet er. For eksempel kan ein vurdere at ein mann med positiv test av sjukdommen dengue i India til å sannsynlegvis ikkje ha dengue til tross for ein test som måler riktig i 95% av tilfella. Ein vil få svært låg sannsyn frå Teorems likning om ein vurderer sannsynet for P(H) til å vere basert på at det er 25 av ein milliard menneske i India som til ein kvar tid har dengue. Men P(H) er subjektiv og kan bli sett til at mannen kjem frå ein landsdel der 15 av 600 har dengue og vil med det få svært mykje større sannsyn for at han har dengue. Bestemminga av kva utval ein reknar frå i P(H) kallast for ein vurdering av baseraten og er eit viktig tema i sannsynsberekningane til Bayesianismen. 

Vurderinga av baseraten vil vere subjektiv og kan variere frå person til person som kan skape forvirring og feilvurdering. For å løyse eit slikt problem er replikasjon viktig. Viktigheita av replikasjon ser ein tydeleg i Teorems likning då fleire betinga uavhengige testar gir sannsynet for at testen for dengue stemmer ein verdi som indikerer at han svært sannsynleg har dengue. 
